# Generated by Django 3.2.8 on 2021-10-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stuname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
