str1="hello"
list1=[1,2,3,4,5]
tup1=(1,2,3,4,5,2,3,1)
#string
print("....................string..............")
print("length of string")
print(len(str1))
print("count of character")
print(str1.count('l'))
print("string is lower?")
print(str1.islower())
print("string is numeric?")
print(str1.isnumeric())
print("string upper case")
print(str1.upper())
#list
print("..................list............")
print("list value at index 1")
print(list1[1])
print("append list")
list1.append(23)
print(list1)
print("pop list")
list1.pop()
print(list1)
print("reverse list")
list1.reverse()
print(list1)
#tuple
print("...................tuple...............")
print("count of character")
print(tup1.count(2))
print("find value of index")
print(tup1.index(5))
