# Generated by Django 3.2.8 on 2021-10-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_student_stuname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stuname',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
